-- From "Fruit Farming (B42)" by leina (Steam Workshop 3779625821), built into
-- HARMONIE - From Garden to Plate with credit -- see 42/CREDITS.txt. Unchanged.
-- generated by pz-sprite-forge/examples/ff_wire_mod.py -- do not edit by hand
-- FruitFarming's own growth sprites: one ff_<crop>_01 sheet per crop (tiledef ids
-- 2100 up), 32 sprites each -- healthy 0-7, unhealthy 8-15, dying 16-23, dead
-- 24-31, one per growth stage. getSpriteName indexes these with nbOfGrow (1-based).
-- A perennial's column 7 is the plant after harvest (see the end of this file).
-- Trampled art stays borrowed from the vanilla crop FF_farmingConf.lua assigns.
require "Farming/farming_vegetableconf"
require "Farming/FF_farmingConf"
if not farming_vegetableconf then return end

local KINDS = { sprite = 0, unhealthySprite = 8, dyingSprite = 16, deadSprite = 24 }
local SHEETS = {}

local function useSheet(key, sheet)
    -- a crop FF_farmingConf.lua disabled (missing vanilla source) keeps no props
    if not farming_vegetableconf.props[key] then return end
    for kind, base in pairs(KINDS) do
        local names = {}
        for i = 0, 7 do names[#names + 1] = sheet .. "_" .. (base + i) end
        farming_vegetableconf[kind] = farming_vegetableconf[kind] or {}
        farming_vegetableconf[kind][key] = names
    end
    -- the picture the seed tooltip shows: the crop in fruit
    farming_vegetableconf.props[key].texture = sheet .. "_6"
    SHEETS[key] = sheet
end

-- Perennials keep their size after harvest. Vanilla's harvest() puts a growBack crop
-- back to nbOfGrow = growBack and grows it one step, and sprite[growBack + 1] is the
-- young plant of the first growth: a fruit tree shrank to a sapling every time it was
-- picked. Column 7 of a perennial's sheet is its fruiting plant with the fruit taken
-- off. While a plant regrows (growBack < nbOfGrow < harvestLevel) after it has fruited
-- -- the sprite it shows now is column 6 (in fruit) or 7 (picked) -- it shows column 7
-- in the health row vanilla chose; bloom and fruit then follow as usual. A first growth
-- never shows column 6 or 7 at those stages, so it is untouched. The sprite name is
-- saved with the plant and sent to clients, so this holds across save/load and in
-- multiplayer, where getSpriteName runs with SFarmingSystem on the server.
local function column(name, sheet)
    if type(name) ~= "string" then return nil end
    local n = string.match(name, "^" .. sheet .. "_(%d+)$")
    return n and tonumber(n) or nil
end

local vanillaGetSpriteName = farming_vegetableconf.getSpriteName
if vanillaGetSpriteName then
    farming_vegetableconf.getSpriteName = function(plant)
        local name = vanillaGetSpriteName(plant)
        local sheet = plant and SHEETS[plant.typeOfSeed]
        if not sheet or not name then return name end
        local props = farming_vegetableconf.props[plant.typeOfSeed]
        local nb = tonumber(plant.nbOfGrow)
        if not (props and props.growBack and nb) then return name end
        if nb <= props.growBack or nb >= (props.harvestLevel or 6) then return name end
        local now, new = column(plant.spriteName, sheet), column(name, sheet)
        if not (now and new) or now % 8 < 6 then return name end
        return sheet .. "_" .. (new - new % 8 + 7)
    end
end

useSheet("FFApple", "ff_apple_01")
useSheet("FFPear", "ff_pear_01")
useSheet("FFPeach", "ff_peach_01")
useSheet("FFCherry", "ff_cherry_01")
useSheet("FFOrange", "ff_orange_01")
useSheet("FFLemon", "ff_lemon_01")
useSheet("FFLime", "ff_lime_01")
useSheet("FFGrapefruit", "ff_grapefruit_01")
useSheet("FFAvocado", "ff_avocado_01")
useSheet("FFMango", "ff_mango_01")
useSheet("FFOlive", "ff_olive_01")
useSheet("FFCoffee", "ff_coffee_01")
useSheet("FFPeanuts", "ff_peanut_01")
useSheet("FFRice", "ff_rice_01")
useSheet("FFBanana", "ff_banana_01")
useSheet("FFPineapple", "ff_pineapple_01")
useSheet("FFGrapes", "ff_grape_01")
useSheet("FFGinger", "ff_ginger_01")
