-- GENERATED by mods/HARMONIE_TheWayToAttack/tools/gen_sounds.py -- do not edit.
-- Length of every sound in ms (a working sound is re-played every LENGTH).
TWASound = TWASound or {}
TWASound.LENGTH = {
    TWA_Hammer = 500,
    TWA_HammerWood = 300,
    TWA_Knap = 250,
    TWA_BigHit = 1600,
    TWA_Tension = 2400,
    TWA_Fanfare = 1800,
    TWA_Smash = 1000,
    TWA_Whetstone = 600,
    TWA_Saw = 500,
    TWA_Weld = 600,
    TWA_Screw = 500,
    TWA_Wrap = 600,
    TWA_Grind = 500,
    TWA_Bellows = 800,
    TWA_Quench = 699,
    TWA_Pour = 600,
    TWA_Coat = 500,
    TWA_Sew = 500,
    TWA_Drill = 500,
    TWA_Carve = 330,
    TWA_Craft = 1000,
    TWA_Success = 600,
    TWA_Fail = 500,
}
