#!/usr/bin/env python3
"""HARMONIE - Home Medic: loudness versions of the delirium sounds.

The delirium hallucination sounds are played with
getSoundManager():playUISound(name) on the player's own machine. The game's
per-sound user volume does not reach UI sounds (found in The Way To Attack,
round 14), so loudness is chosen by FILE: every delirium sound gets copies
at LEVELS percent of the original, and HARMONIE_DeliriumAudio.lua picks the
copy nearest to the player's volume setting (100 = the original file).

Writes
  ../42/media/sound/HARMONIE_Delirium/<file>_v<level>.ogg
  ../42/media/scripts/HARMONIE_HomeMedic_DeliriumSounds.txt   (sound defs)
  ../42/media/lua/shared/HARMONIEHomeMedic/HARMONIE_DeliriumLevels.lua
Reads the sound names and files from EHR's own scripts/EHR_Sounds.txt.
Needs: pip install soundfile numpy
"""
import os, re
import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
MEDIA = os.path.join(HERE, "..", "42", "media")
LEVELS = [25, 50, 75, 125, 150]          # 100 = the original, 0 = muted in Lua
OUT_DIR = "HARMONIE_Delirium"


def delirium_sounds():
    s = open(os.path.join(MEDIA, "scripts", "EHR_Sounds.txt"), encoding="utf-8").read()
    out = []
    for m in re.finditer(r"sound\s+(EHRDelirium\w+)\s*\{(.*?)\n    \}", s, re.S):
        body = m.group(2)
        f = re.search(r"file\s*=\s*([^,\s]+)", body).group(1)
        cat = re.search(r"category\s*=\s*(\w+)", body)
        dist = re.search(r"distanceMax\s*=\s*([\d.]+)", body)
        out.append((m.group(1), f, cat.group(1) if cat else "Player", dist.group(1) if dist else "18"))
    return out


def scaled(data, level):
    y = data * (level / 100.0)
    if level > 100:
        y = np.tanh(y)  # soft limiter: near-linear when quiet, no hard clipping
    return y.astype(np.float32)


def write_ogg(path, y, sr):
    # libsndfile's Vorbis encoder crashes on one huge write -- feed it blocks.
    with sf.SoundFile(path, "w", sr, y.shape[1], format="OGG", subtype="VORBIS") as f:
        for i in range(0, len(y), 8192):
            f.write(y[i:i + 8192])


def main():
    sounds = delirium_sounds()
    os.makedirs(os.path.join(MEDIA, "sound", OUT_DIR), exist_ok=True)
    defs = ["/* GENERATED by mods/HARMONIE_HomeMedic/tools/gen_delirium_volumes.py -- do not edit.",
            "   Loudness copies of the delirium sounds (HARMONIE_DeliriumAudio.lua picks one). */",
            "module Base", "{"]
    for name, rel, cat, dist in sounds:
        src = os.path.join(MEDIA, "..", rel)
        data, sr = sf.read(src, dtype="float32", always_2d=True)
        base = os.path.splitext(os.path.basename(rel))[0]
        for lv in LEVELS:
            fn = "%s_v%d.ogg" % (base, lv)
            write_ogg(os.path.join(MEDIA, "sound", OUT_DIR, fn), scaled(data, lv), sr)
            defs += ["    sound %s_v%d" % (name, lv), "    {", "        category = %s," % cat,
                     "        clip", "        {", "            file = media/sound/%s/%s," % (OUT_DIR, fn),
                     "            distanceMax = %s," % dist, "        }", "    }", ""]
    defs.append("}")
    with open(os.path.join(MEDIA, "scripts", "HARMONIE_HomeMedic_DeliriumSounds.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(defs) + "\n")
    with open(os.path.join(MEDIA, "lua", "shared", "HARMONIEHomeMedic", "HARMONIE_DeliriumLevels.lua"), "w", encoding="utf-8", newline="\n") as f:
        f.write("-- GENERATED by mods/HARMONIE_HomeMedic/tools/gen_delirium_volumes.py -- do not edit.\n")
        f.write("HARMONIE_HomeMedic_DeliriumLevels = { %s }\n" % ", ".join(str(x) for x in LEVELS))
    print("sounds:", len(sounds), "levels:", LEVELS)


if __name__ == "__main__":
    main()
