require "Items/ProceduralDistributions"
require "Items/ItemPicker"

-- Weight matched to upstream's 2026-09-07 loot rebalance: every upstream gun
-- moved from 0.3 to 0.3. Ours tracks theirs so the MTL30 is no more common
-- than any other rifle.
if SandboxVars and SandboxVars.ModernFirearmsSystemSandboxGun and SandboxVars.ModernFirearmsSystemSandboxGun._MFS_MTL30_cat_Spawn == false then return end

table.insert(ProceduralDistributions.list["GunStoreShelf"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["GunStoreShelf"].items, 0.13);
table.insert(ProceduralDistributions.list["PlankStashGun"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["PlankStashGun"].items, 0.13);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 0.13);
table.insert(ProceduralDistributions.list["ArmyStorageGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["ArmyStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions.list["GunStoreCounter"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["GunStoreCounter"].items, 0.13);
table.insert(ProceduralDistributions.list["PoliceStorageGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["PoliceStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions.list["PawnShopGunsSpecial"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["PawnShopGunsSpecial"].items, 0.13);
table.insert(ProceduralDistributions.list["GunStoreDisplayCase"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["GunStoreDisplayCase"].items, 0.13);
table.insert(ProceduralDistributions.list["GarageFirearms"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["GarageFirearms"].items, 0.13);
table.insert(ProceduralDistributions.list["DrugLabGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["DrugLabGuns"].items, 0.13);
table.insert(ProceduralDistributions.list["ArmySurplusCases"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["ArmySurplusCases"].items, 0.13);
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.13);
table.insert(ProceduralDistributions.list["LockerArmyBedroomHome"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["LockerArmyBedroomHome"].items, 0.13);
table.insert(ProceduralDistributions.list["PrisonArmoryShotguns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions.list["PrisonArmoryShotguns"].items, 0.13);

-- 新增建筑容器（list）
table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "Base.MFS_MTL30_cat");
table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 0.13);
table.insert(SuburbsDistributions["Bag_DuffelBagTINT"].items, "Base.MFS_MTL30_cat");
table.insert(SuburbsDistributions["Bag_DuffelBagTINT"].items, 0.13);
table.insert(ProceduralDistributions["list"]["ClosetInstruments"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["ClosetInstruments"].items, 0.13);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceOutfit"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceOutfit"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStateOutfit"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceStateOutfit"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStateTools"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceStateTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceTools"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PoliceTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PrisonStorageGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["PrisonStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["RangerTools"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["RangerTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["SWATStorageGuns"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["SWATStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, "Base.MFS_MTL30_cat");
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, 0.13);

-- ========== vehicle 车辆战利品池 ✅ 修正分支 ==========
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, 0.13);
table.insert(VehicleDistributions["SurvivalistSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["SurvivalistSeatFront"].items, 0.13);
table.insert(VehicleDistributions["SurvivalistSeatRear"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["SurvivalistSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceTruckBed"].items, 0.13);
table.insert(VehicleDistributions["PoliceSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceSeatFront"].items, 0.13);
table.insert(VehicleDistributions["RangerTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["RangerTruckBed"].items, 0.13);
table.insert(VehicleDistributions["RangerSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["RangerSeatFront"].items, 0.13);
table.insert(VehicleDistributions["RangerSeatRear"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["RangerSeatRear"].items, 0.13);
table.insert(VehicleDistributions["HunterTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["HunterTruckBed"].items, 0.13);
table.insert(VehicleDistributions["HunterSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["HunterSeatFront"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["ArmyLightTruckBed"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["ArmyLightSeatFront"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightSeatRear"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["ArmyLightSeatRear"].items, 0.13);
table.insert(VehicleDistributions["ArmyHeavyTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["ArmyHeavyTruckBed"].items, 0.13);
table.insert(VehicleDistributions["ArmyHeavySeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["ArmyHeavySeatFront"].items, 0.13);
table.insert(VehicleDistributions["PrisonGuardSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PrisonGuardSeatFront"].items, 0.13);
table.insert(VehicleDistributions["BanditTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["BanditTruckBed"].items, 0.13);
table.insert(VehicleDistributions["BanditSeatRear"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["BanditSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceSWATTruckBed"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceSWATTruckBed"].items, 0.13);
table.insert(VehicleDistributions["PoliceSWATSeatRear"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceSWATSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceStateSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceStateSeatFront"].items, 0.13);
table.insert(VehicleDistributions["PoliceDetectiveSeatFront"].items, "Base.MFS_MTL30_cat");
table.insert(VehicleDistributions["PoliceDetectiveSeatFront"].items, 0.13);
