-- GENERATED by tools/gen_cook_sounds.py: each cooking sound's length in ms
HARMONIE_GTP = HARMONIE_GTP or {}
HARMONIE_GTP.CookSoundLength = {
    GTPC_Chop = 220,
    GTPC_Slice = 160,
    GTPC_Scrub = 349,
    GTPC_Scrape = 220,
    GTPC_Spread = 300,
    GTPC_Thump = 250,
    GTPC_Crack = 300,
    GTPC_Sizzle = 400,
    GTPC_Toss = 400,
    GTPC_Stir = 450,
    GTPC_Whisk = 300,
    GTPC_Grind = 349,
    GTPC_Squish = 220,
    GTPC_Pour = 300,
    GTPC_Bubble = 500,
    GTPC_Roll = 400,
    GTPC_Slip = 300,
    GTPC_Excellent = 960,
    GTPC_Good = 780,
    GTPC_Bad = 880,
    GTPC_Miss = 960,
}
HARMONIE_GTP.CookSoundLevels = { 25, 50, 75, 100, 150 }
