#!/usr/bin/env python3
"""HARMONIE - From Garden to Plate: the items behind each vanilla tag the
cooking tools use (0.13.5).

Why: in B42 item:hasTag() takes an ItemTag object, not a "base:fork" string.
Called with a string it throws "No implementation found for function:
hasTag(...)" -- and the game writes that whole exception to console.txt
even inside pcall, every frame the Cooking tab is open (console.txt of
2026-10-09: 1618 times). So the tab never asks the game about a tag: it
looks the item TYPES up in this table, made from vanilla's own scripts
(mods/_VanillaReference_B42/tags_index.txt, rebuilt by build_index.py).

Writes ../42/media/lua/shared/HARMONIEGardenToPlate/HARMONIE_CookTagItems.lua
(one statement per tag -- no big table constructor, Kahlua-safe).
"""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "..", "..", "_VanillaReference_B42", "tags_index.txt")
DATA = os.path.join(HERE, "..", "42", "media", "lua", "shared", "HARMONIEGardenToPlate", "HARMONIE_CookData.lua")
OUT = os.path.join(HERE, "..", "42", "media", "lua", "shared", "HARMONIEGardenToPlate", "HARMONIE_CookTagItems.lua")

tags, cur = {}, None
for line in open(REF, encoding="utf-8"):
    m = re.match(r"\[(.+?)\]\s*\d+", line)
    if m:
        cur = m.group(1); tags[cur] = []; continue
    if cur and line.startswith("  ") and line.strip():
        tags[cur].append(line.strip())

used = sorted(set(re.findall(r'"(base:[a-z0-9_]+)"', open(DATA, encoding="utf-8").read())))
missing = [t for t in used if not tags.get(t)]
if missing:
    raise SystemExit("tags used by the cooking data but not in vanilla: %s" % missing)

out = ["-- GENERATED by mods/HARMONIE_GardenToPlate/tools/gen_cook_tag_items.py from",
       "-- vanilla B42's scripts (mods/_VanillaReference_B42/tags_index.txt). Do not edit by hand.",
       "-- tag -> the item types that carry it (the cooking tab never calls item:hasTag",
       "-- with a string: B42 throws on that, see the generator's header).",
       "HARMONIE_GTP = HARMONIE_GTP or {}",
       "HARMONIE_GTP.Cook = HARMONIE_GTP.Cook or {}",
       "local T = {}",
       "HARMONIE_GTP.Cook.TAG_ITEMS = T"]
for t in used:
    out.append('T["%s"] = { %s }' % (t, ", ".join('"%s"' % x for x in tags[t])))
open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("tags", len(used), "items", sum(len(tags[t]) for t in used), "->", os.path.relpath(OUT, HERE))
