#!/usr/bin/env python3
"""HARMONIE - From Garden to Plate: writes HARMONIE_CookVanilla.lua from the
vanilla Build 42 reference in mods/_VanillaReference_B42 (build_index.py).

  K.VANILLA.templates[template][fullType] = points   (EvolvedRecipe use)
  K.VANILLA.cooked[template][fullType]    = true     ("|Cooked": only cooked)
  K.VANILLA.recipes[scriptName] = { base, result, max, template, water, name }
Only item names and numbers -- the Cooking tab uses it to show what vanilla
accepts before a base is at hand, and the tests check every dish against it.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "..", "..", "_VanillaReference_B42")
OUT = os.path.join(HERE, "..", "42", "media", "lua", "shared", "HARMONIEGardenToPlate", "HARMONIE_CookVanilla.lua")

tpl, cooked, cur = {}, {}, None
for l in open(os.path.join(REF, "evolvedrecipe_ingredients.txt"), encoding="utf-8"):
    m = re.match(r"\[(.+)\] \d+ items", l)
    if m:
        cur = m.group(1); tpl[cur] = {}; cooked[cur] = set(); continue
    if cur and l.startswith("  "):
        p = [x.strip() for x in l.split(" | ")]
        full, pts = p[0], p[-1]
        num = re.match(r"([0-9.]+)", pts)
        tpl[cur][full] = float(num.group(1)) if num else 0
        if "|Cooked" in pts: cooked[cur].add(full)
recipes = []
for l in open(os.path.join(REF, "evolvedrecipes_index.txt"), encoding="utf-8"):
    if l.startswith("#") or not l.strip(): continue
    p = [x.strip() for x in l.split(" | ")]
    recipes.append((p[0], p[1], p[2], p[3], p[4], p[5], "MinimumWater" in p[6]))

def q(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
def num(v): return ("%g" % v)

out = ["-- HARMONIE - From Garden to Plate: vanilla Build 42 evolved-recipe data for the Cooking tab.",
       "-- Generated by tools/gen_cook_vanilla.py from mods/_VanillaReference_B42 -- do not edit by hand.",
       "HARMONIE_GTP = HARMONIE_GTP or {}",
       "HARMONIE_GTP.Cook = HARMONIE_GTP.Cook or {}",
       "local V = { templates = {}, cooked = {}, recipes = {} }",
       "HARMONIE_GTP.Cook.VANILLA = V"]
for t in sorted(tpl, key=str.lower):
    items = ", ".join("[%s] = %s" % (q(k), num(v)) for k, v in sorted(tpl[t].items(), key=lambda x: x[0].lower()))
    out.append("V.templates[%s] = { %s }" % (q(t), items))
    if cooked[t]:
        out.append("V.cooked[%s] = { %s }" % (q(t), ", ".join("[%s] = true" % q(k) for k in sorted(cooked[t], key=str.lower))))
for n, base, res, mx, name, t, water in recipes:
    out.append("V.recipes[%s] = { base = %s, result = %s, max = %s, name = %s, template = %s, water = %s }"
               % (q(n), q(base), q(res), mx or "0", q(name), q(t), "true" if water else "false"))
open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("templates %d, recipes %d -> %s" % (len(tpl), len(recipes), os.path.relpath(OUT, HERE)))
