require 'Items/ProceduralDistributions'
require "Items/ItemPicker"

if SandboxVars and SandboxVars.ModernFirearmsSystemSandboxGun and SandboxVars.ModernFirearmsSystemSandboxGun._ROSE_cat_Spawn == false then return end

table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 0.13);

-- 新增建筑容器（list）
table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "Base.ROSE_cat");
table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 0.13);
table.insert(SuburbsDistributions["Bag_DuffelBagTINT"].items, "Base.ROSE_cat");
table.insert(SuburbsDistributions["Bag_DuffelBagTINT"].items, 0.13);
table.insert(ProceduralDistributions["list"]["ClosetInstruments"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["ClosetInstruments"].items, 0.13);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceOutfit"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceOutfit"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStateOutfit"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceStateOutfit"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStateTools"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceStateTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PoliceTools"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PoliceTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["PrisonStorageGuns"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["PrisonStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["RangerTools"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["RangerTools"].items, 0.13);
table.insert(ProceduralDistributions["list"]["SWATStorageGuns"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["SWATStorageGuns"].items, 0.13);
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, "Base.ROSE_cat");
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, 0.13);

-- ========== vehicle 车辆战利品池 ✅ 修正分支 ==========
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, 0.13);
table.insert(VehicleDistributions["SurvivalistSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["SurvivalistSeatFront"].items, 0.13);
table.insert(VehicleDistributions["SurvivalistSeatRear"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["SurvivalistSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceTruckBed"].items, 0.13);
table.insert(VehicleDistributions["PoliceSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceSeatFront"].items, 0.13);
table.insert(VehicleDistributions["RangerTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["RangerTruckBed"].items, 0.13);
table.insert(VehicleDistributions["RangerSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["RangerSeatFront"].items, 0.13);
table.insert(VehicleDistributions["RangerSeatRear"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["RangerSeatRear"].items, 0.13);
table.insert(VehicleDistributions["HunterTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["HunterTruckBed"].items, 0.13);
table.insert(VehicleDistributions["HunterSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["HunterSeatFront"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["ArmyLightTruckBed"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["ArmyLightSeatFront"].items, 0.13);
table.insert(VehicleDistributions["ArmyLightSeatRear"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["ArmyLightSeatRear"].items, 0.13);
table.insert(VehicleDistributions["ArmyHeavyTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["ArmyHeavyTruckBed"].items, 0.13);
table.insert(VehicleDistributions["ArmyHeavySeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["ArmyHeavySeatFront"].items, 0.13);
table.insert(VehicleDistributions["PrisonGuardSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PrisonGuardSeatFront"].items, 0.13);
table.insert(VehicleDistributions["BanditTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["BanditTruckBed"].items, 0.13);
table.insert(VehicleDistributions["BanditSeatRear"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["BanditSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceSWATTruckBed"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceSWATTruckBed"].items, 0.13);
table.insert(VehicleDistributions["PoliceSWATSeatRear"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceSWATSeatRear"].items, 0.13);
table.insert(VehicleDistributions["PoliceStateSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceStateSeatFront"].items, 0.13);
table.insert(VehicleDistributions["PoliceDetectiveSeatFront"].items, "Base.ROSE_cat");
table.insert(VehicleDistributions["PoliceDetectiveSeatFront"].items, 0.13);
