#!/usr/bin/env python3
"""Builds the vanilla Build 42 reference indexes in this folder.

Usage:  python3 build_index.py <path to ProjectZomboid/media/scripts> [<path to Translate/EN/ItemName.json>]
Writes (next to this file):
  items_index.txt          every item: full type | English name | ItemType | DisplayCategory | Weight | file
  food_index.txt           every food: hunger, thirst, calories, carbs, fat, protein, fresh/rotten days,
                           FoodType, cookable, EvolvedRecipe (recipe:hunger points), Tags
  evolvedrecipes_index.txt every evolved recipe: base item, result item, MaxItems, Name, Template, ...
  evolvedrecipe_ingredients.txt  for each evolved recipe template: the items that may go in, with their points
  craftrecipes_index.txt   every craftRecipe: file, timedAction, time, Tags, skills, inputs -> outputs
  tags_index.txt           every item tag -> the items that carry it
  (raw/ holds a local, untracked copy of the vanilla files themselves -- see README.txt)
Nothing here is loaded by the game: this folder has no mod.info.
"""
import os, re, sys, json, collections

HERE = os.path.dirname(os.path.abspath(__file__))


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return re.sub(r"//[^\n]*", "", s)


def blocks(text, kind):
    """(name, body) of every `kind Name { ... }` block (braces matched)."""
    out = []
    # names may hold spaces ("evolvedrecipe Stir fry Griddle Pan {")
    for m in re.finditer(r"\b%s[ \t]+([^\n{}]+?)\s*\{" % kind, text):
        i, depth = m.end(), 1
        while i < len(text) and depth:
            if text[i] == "{": depth += 1
            elif text[i] == "}": depth -= 1
            i += 1
        out.append((m.group(1).strip(), text[m.end():i - 1]))
    return out


def props(body):
    """top-level `Key = value,` pairs of a block body (nested blocks skipped)."""
    d, depth, line = collections.OrderedDict(), 0, ""
    for ch in body:
        if ch == "{": depth += 1
        elif ch == "}": depth -= 1
        elif depth == 0:
            if ch in ",\n":
                if "=" in line:
                    k, v = line.split("=", 1)
                    k, v = k.strip(), v.strip()
                    if k and k not in d: d[k] = v
                line = ""
            else:
                line += ch
    return d


def sub_block(body, name):
    m = re.search(r"\b%s\s*\{" % name, body)
    if not m: return ""
    i, depth = m.end(), 1
    while i < len(body) and depth:
        if body[i] == "{": depth += 1
        elif body[i] == "}": depth -= 1
        i += 1
    return body[m.end():i - 1]


def lines_of(block):
    return [re.sub(r"\s+", " ", l.strip().rstrip(",")) for l in block.split("\n") if l.strip() and l.strip() not in "{}"]


def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    root = sys.argv[1]
    names = {}
    if len(sys.argv) > 2 and os.path.exists(sys.argv[2]):
        names = json.load(open(sys.argv[2], encoding="utf-8"))
    files = []
    for dp, _, fs in os.walk(root):
        for f in sorted(fs):
            if f.endswith(".txt"): files.append(os.path.join(dp, f))
    items, recipes, evolved, modules = [], [], [], {}
    for path in sorted(files):
        rel = os.path.relpath(path, root).replace(os.sep, "/")
        text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
        for mname, mbody in blocks(text, "module"):
            for n, b in blocks(mbody, "item"):
                items.append((mname + "." + n, props(b), rel))
            for n, b in blocks(mbody, "craftRecipe"):
                recipes.append((n, b, rel))
            for n, b in blocks(mbody, "evolvedrecipe"):
                evolved.append((n, props(b), rel))
    items.sort(key=lambda x: x[0].lower())

    def disp(full, p):
        return names.get(full) or p.get("DisplayName") or ""

    head = "# Vanilla Project Zomboid Build 42 -- generated by build_index.py from media/scripts (do not edit by hand)\n"
    with open(os.path.join(HERE, "items_index.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# full type | English name | ItemType | DisplayCategory | Weight | Icon | file\n")
        for full, p, rel in items:
            f.write(" | ".join([full, disp(full, p), p.get("ItemType", ""), p.get("DisplayCategory", ""), p.get("Weight", ""), p.get("Icon", ""), rel]) + "\n")

    food = [(full, p, rel) for full, p, rel in items if p.get("ItemType", "").endswith("food") or "HungerChange" in p or "Calories" in p]
    cols = ["HungerChange", "ThirstChange", "Calories", "Carbohydrates", "Lipids", "Proteins", "UnhappyChange", "BoredomChange",
            "DaysFresh", "DaysTotallyRotten", "FoodType", "IsCookable", "MinutesToCook", "MinutesToBurn", "Spice",
            "DangerousUncooked", "Poison", "EvolvedRecipe", "EvolvedRecipeName", "Tags"]
    with open(os.path.join(HERE, "food_index.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# full type | English name | " + " | ".join(cols) + " | file\n")
        f.write("# (empty = not set in the script: the game's default applies)\n")
        for full, p, rel in food:
            f.write(" | ".join([full, disp(full, p)] + ["%s=%s" % (c, p[c]) if c in p else "" for c in cols] + [rel]) + "\n")

    with open(os.path.join(HERE, "evolvedrecipes_index.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# script name | BaseItem | ResultItem | MaxItems | Name | Template | other keys | file\n")
        for n, p, rel in evolved:
            other = ", ".join("%s=%s" % (k, v) for k, v in p.items() if k not in ("BaseItem", "ResultItem", "MaxItems", "Name", "Template"))
            f.write(" | ".join([n, p.get("BaseItem", ""), p.get("ResultItem", ""), p.get("MaxItems", ""), p.get("Name", ""), p.get("Template", ""), other, rel]) + "\n")

    # which items may go into which evolved recipe (the item's EvolvedRecipe key)
    by_recipe = collections.OrderedDict()
    for full, p, rel in items:
        er = p.get("EvolvedRecipe")
        if not er: continue
        for part in er.split(";"):
            part = part.strip()
            if not part: continue
            rname, _, pts = part.partition(":")
            by_recipe.setdefault(rname.strip(), []).append((full, disp(full, p), pts.strip()))
    with open(os.path.join(HERE, "evolvedrecipe_ingredients.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# For each evolved-recipe name used in items' EvolvedRecipe: the items allowed in, and their points\n")
        f.write("# (points = hunger used per addition; '|Cooked' = only when cooked). Matched by the recipe's Template/name.\n")
        for rname in sorted(by_recipe, key=str.lower):
            f.write("\n[%s] %d items\n" % (rname, len(by_recipe[rname])))
            for full, dn, pts in sorted(by_recipe[rname], key=lambda x: x[0].lower()):
                f.write("  %s | %s | %s\n" % (full, dn, pts))

    with open(os.path.join(HERE, "craftrecipes_index.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# One block per craftRecipe: name [file] then its keys, inputs and outputs as written in the script\n")
        for n, b, rel in sorted(recipes, key=lambda x: (x[2], x[0].lower())):
            p = props(b)
            f.write("\n%s  [%s]\n" % (n, rel))
            keys = ", ".join("%s=%s" % (k, v) for k, v in p.items())
            if keys: f.write("  " + keys + "\n")
            for l in lines_of(sub_block(b, "inputs")): f.write("  in : " + l + "\n")
            for l in lines_of(sub_block(b, "outputs")): f.write("  out: " + l + "\n")

    tags = collections.defaultdict(list)
    for full, p, rel in items:
        for t in (p.get("Tags") or "").split(";"):
            t = t.strip()
            if t: tags[t].append(full)
    with open(os.path.join(HERE, "tags_index.txt"), "w", encoding="utf-8") as f:
        f.write(head + "# item tag -> items that carry it\n")
        for t in sorted(tags, key=str.lower):
            f.write("\n[%s] %d\n  %s\n" % (t, len(tags[t]), "\n  ".join(sorted(tags[t], key=str.lower))))

    print("items %d, food %d, craftRecipes %d, evolved recipes %d, evolved names %d, tags %d, files %d"
          % (len(items), len(food), len(recipes), len(evolved), len(by_recipe), len(tags), len(files)))


if __name__ == "__main__":
    main()
