-- GENERATED by mods/HARMONIE_GardenToPlate/tools/gen_cook_tag_items.py from
-- vanilla B42's scripts (mods/_VanillaReference_B42/tags_index.txt). Do not edit by hand.
-- tag -> the item types that carry it (the cooking tab never calls item:hasTag
-- with a string: B42 throws on that, see the generator's header).
HARMONIE_GTP = HARMONIE_GTP or {}
HARMONIE_GTP.Cook = HARMONIE_GTP.Cook or {}
local T = {}
HARMONIE_GTP.Cook.TAG_ITEMS = T
T["base:ballpeenhammer"] = { "Base.BallPeenHammer", "Base.BallPeenHammerForged" }
T["base:bowl"] = { "Base.Bowl", "Base.ClayBowl" }
T["base:clubhammer"] = { "Base.BlockMace", "Base.ClubHammer", "Base.ClubHammerForged" }
T["base:dullknife"] = { "Base.BreadKnife", "Base.ButterKnife", "Base.ButterKnife_Gold", "Base.ButterKnife_Silver", "Base.DullBoneKnife", "Base.PlasticKnife", "Base.SharpBone_Long" }
T["base:fork"] = { "Base.Fork", "Base.Fork_Bone", "Base.Fork_Gold", "Base.Fork_Silver", "Base.ForkForged", "Base.PlasticFork", "Base.Spork", "Base.WoodenFork" }
T["base:glassbottle"] = { "Base.BeerImported", "Base.BottleCrafted", "Base.Brandy", "Base.Champagne", "Base.Cider", "Base.CoffeeLiquer", "Base.Curacao", "Base.Gin", "Base.Grenadine", "Base.Port", "Base.Rum", "Base.Scotch", "Base.Sherry", "Base.Tequila", "Base.Vermouth", "Base.Vodka", "Base.Whiskey", "Base.Wine", "Base.Wine2", "Base.Wine2Open", "Base.WineAged", "Base.WineOpen", "Base.WineScrewtop" }
T["base:grater"] = { "Base.CheeseGrater" }
T["base:hammer"] = { "Base.BallPeenHammer", "Base.BallPeenHammerForged", "Base.Hammer", "Base.HammerForged", "Base.HammerStone", "Base.SmithingHammer" }
T["base:meatcleaver"] = { "Base.MeatCleaver", "Base.MeatCleaver_Scrap", "Base.MeatCleaverForged" }
T["base:mortarpestle"] = { "Base.CeramicMortarandPestle", "Base.MortarPestle" }
T["base:scissors"] = { "Base.Multitool", "Base.Scissors", "Base.ScissorsBlunt", "Base.ScissorsBluntMedical", "Base.ScissorsForged" }
T["base:sharpknife"] = { "Base.CrudeKnife", "Base.FightingKnife", "Base.FlintKnife", "Base.HandguardDagger", "Base.Handiknife", "Base.HuntingKnife", "Base.HuntingKnifeForged", "Base.KitchenKnife", "Base.KitchenKnifeForged", "Base.KnifeButterfly", "Base.KnifeFillet", "Base.KnifeParing", "Base.KnifePocket", "Base.KnifeSushi", "Base.LargeKnife", "Base.LargeKnife_Scrap", "Base.LongCrudeKnife", "Base.Machete", "Base.Machete_Crude", "Base.MacheteForged", "Base.MacheteKnife", "Base.Multitool", "Base.RailroadSpikeKnife", "Base.SharpedStone", "Base.SmallKnife", "Base.SteakKnife", "Base.StoneKnifeLong", "Base.StraightRazor", "Base.SwitchKnife" }
T["base:spoon"] = { "Base.PlasticSpoon", "Base.Spoon", "Base.Spoon_Bone", "Base.Spoon_Gold", "Base.Spoon_Silver", "Base.SpoonForged", "Base.Spork", "Base.WoodenSpoon" }
