-- COMPATIBILITY SHIM - safe to delete once upstream migrates its own requires.
--
-- Upstream renamed its AWCWF_* Lua files to EFK_* on 2026-08-30 but did not
-- update a single require statement. Eight requires across four of its files
-- still ask for the old AWCWF_ paths, which no longer exist in its tree. Until
-- this session the community patch happened to satisfy three of them purely
-- because it still shipped files under the old names.
--
-- The patch now overrides upstream's EFK_* files by exact path, which is
-- deterministic instead of load-order dependent. This one-line file keeps the
-- stale upstream requires resolving in the meantime. It holds no data and
-- defines no behaviour.
--
-- Delete this file when upstream's requires point at EFK_ names.

-- Special case: no file has ever existed at this path, in upstream or in the
-- fork. Upstream's Weapon_Inspect_Render.lua has required it since before our
-- fork point and it has always failed. The global it is supposed to provide is
-- declared in client/EFK_GlobalVarsSet.lua, which cannot be required from a
-- shared/ file because shared/ also loads on a dedicated server where client/
-- does not. So declare the global here instead, exactly as EFK_GlobalVarsSet
-- does, and let whichever loads second keep the populated table.
AWCWF_WeaponWithBoltAnim = AWCWF_WeaponWithBoltAnim or {}
